print("Hello Neo")
print(".....")
print("Sorry, not you my mistake!")
name=input("what is your name?")
print("Welcome!", name, "!", "Please answer following question and make your own story")
print()
animal=input("Insert Moon's nationality: ")
gf=input("Inset name of your girfriend: ")
adjective1=input("Insert adjective: ")
color1=input("Insert color: ")
adjective2=input("Insert adjective: ")
noun1=input("Insert food name: ")
noun2=input("Insert other animal: ")
noun3=input("Insert any taste: ")
adjective3=input("Insert any home abject: ")
color2=input("Insert color: ")
noun4=input("Is it new or old?: ")
when=input("Insert any festive day: ")
where=input("Insert the place to avoid: ")
who=input("Insert name of one of your family member: ")
what=input("Insert the most embarassing action: ")
print("This is your TRUE story")
print()
print("I have a companion person", animal, "the name is", gf)
print("She is", adjective1, color1, "and", adjective2)
print("She likes", noun1, noun2, "anything that taste", noun3)
print("When she is angry she often bite", noun4, color2, adjective3)
print("However, I am organising secret trip to", where, "with", who)
print("for", when, "Moon will fall in love with me when she see me", what, "in", where)


